

pathDB: mongodb-deployment-service
user: admin
password: ${ME_CONFIG_MONGODB_ADMINPASSWORD}

namespace: jenkins
countreplic: 1
secret: UGFzc3dvcmQxMjM0
tag_name: latest

env:
  dev: dev
  prod: prod
