apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.countreplic }}
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
        - name: app
          image: morovol/fastapi:latest
          env:
            - name: MONGOHOST
              value: {{ .Values.pathDB }}
          ports:
            - containerPort: 8000

